name: CI

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  workflow_dispatch:

jobs:
  docker:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Start Containers
        run: docker-compose -f "docker-compose.yaml" up build

      - name: List Docker Images
        run: docker images ls
