name: CI

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

  workflow_dispatch:

jobs:
  docker:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "${{ secrets.DOCKERHUB_USER }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Images
        id: docker-builder
        run: |
          echo "-----Building Docker Images-----"
          docker-compose -f docker-compose.yaml build
      
      - name: List Docker Images
        run: | 
          eco $${{ steps.docker-builder.outputs.name }}
          docker images ls
