name: GCloud Build
on:
  workflow_dispatch:
  
env:
  GAR_INFO: us-central1-docker.pkg.dev/triangulum-ctv/stans-robot-shop
  CART_APP_NAME: rs-cart
  SHIPPING_APP_NAME: rs-shipping
  CATALOGUE_APP_NAME: rs-catalogue
  DISPATCH_APP_NAME: rs-dispatch
  MONGO_APP_NAME: rs-mongodb
  MYSQL_APP_NAME: rs-mysql-db
  PAYMENT_APP_NAME: rs-payment
  RATINGS_APP_NAME: rs-ratings
  USER_APP_NAME: rs-user
  WEB_APP_NAME: rs-web
  REDIS_APP_NAME: redis
  RABBITMQ_APP_NAME: rabbitmq

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: first-step
      uses: actions/checkout@v3
      with:
        path: shipping
    - name: second-step
      run: |
        ls -lR
        pwd